name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Node.js and npm
        uses: actions/setup-node@v3
        with:
          node-version: '14'
        
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.19.6'

      - name: Deploy to GitHub Pages
        run: |
          if [ -d "build/web" ]; then
            npx gh-pages -d build/web
          else
            echo "Error: 'build/web' directory not found. Skipping deployment."
          fi

